public without sharing class ConstantsUtil {
    public final static String QUICKSTAT = 'QUICKSTAT';
    public final static String PROTRAC = 'PROTRAC';
    public final static String PROTRAC_APH_SHIPMENT = 'Protrac_APH_Shipment';
    public final static String PROTRAC_DP_BOOKING = 'Protrac_DP_Booking';
    public final static String PROTRAC_DP_RECEIPT = 'Protrac_DP_Receipt';
    public final static String PROTRAC_MANUFACTURING_STATUS = 'Protrac_Manufacturing_Status';
    public final static String PROTRAC_PATIENT_REGISTRATION = 'Protrac_Patient_Registration';
    public final static String QUICKSTAT_CREATE_SHIPMENT = 'QuickStat_Create_Shipment';
    public enum Category {WINTER, SPRING, SUMMER, FALL}

}